### ISSUE TITLE
Android Boot camera.msm8974.so Error

### ISSUE THREAD

**Issue by alokhan** [sonyxperiadev/device-sony-aries#36]
Hi,

I have few issues with the AOSP 6.0 for Z3C. 

First I had to comment these lines to get it to compile.: 

`enum mdp_rev {
    MDSS_MDP_HW_REV_100 = 0x10000000,
    MDSS_MDP_HW_REV_101 = 0x10010000, //8x26
    MDSS_MDP_HW_REV_102 = 0x10020000,
};`

(file: hardware/qcom/display/msm8974/libqdutils/mdp_version.h)

Secondly after having a successful build 

Android is starting but it is stuck in the boot process.
There is a error in the camera.msm8974.so (replacing this file by the same file but from the Sony beta marshmallow rom will get the phone to boot).

`/system/lib/hw/camera.msm8974.so (qcamera::QCamera3HardwareInterface::initStaticMetadata(unsigned int)+1377)`

Do you also have any idea why ?

Thanks

**Comment by jerpelea** [comment]
please follow the guide 
you are compiling with wrong headers
