### ISSUE TITLE
Missing ro.qti.sensors values

### ISSUE THREAD

**Issue by danielegobbetti** [sonyxperiadev/device-sony-aries#59]
On AOSP 6.0/6.01/7 the sensor appears to be present:

```
aries:/ # dumpsys deviceidle
...
  mMotionSensor={Sensor name="Significant Motion Detector", vendor="QTI", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.12998962, minDelay=-1}
...
```

However apps cannot read values from it. For instance: https://play.google.com/store/apps/details?id=de.j4velin.pedometer works perfectly with stock ROMs, but cannot use the sensor on AOSP.

**Comment by danielegobbetti** [comment]
After changing the following values in ``device/sony/shinano/platform.mk``:
```
ro.qti.sensors.step_detector=true
ro.qti.sensors.step_counter=true
ro.qti.sensors.game_rv=true
ro.qti.sensors.georv=true
ro.qti.sensors.tilt_detector=true
```

The step detector works and doze mode seems to be triggered correctly by the significant motion sensor.

This is working fine on aries (z3 compact). I'm not sure if I should make a pull request on the shinano repo as it would affect other devices where I cannot test.

**Comment by jerpelea** [comment]
you are enabling more sensors that the ones stated in the commit message

**Comment by danielegobbetti** [comment]
@jerpelea I can gladly do a proper pull request if you think it makes sense at the shinano platform level, just give me a go :)

**Comment by jerpelea** [comment]
please do

**Comment by jerpelea** [comment]
please PR

**Comment by danielegobbetti** [comment]
Made two PRs (n-mr1 and n-mr0) in the shinano repo. I included only the step sensor/detector sensors.

**Comment by jerpelea** [comment]
plase do the same for kitakami loire tone and yoshino

**Comment by danielegobbetti** [comment]
Will do but it will take some time, if someone beats me to it no offense taken :)
